version: "3.8"

networks:

services:
  artemiz_site:
    env_file:
      - .env
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${DOCKER_UID:-1000}
        - GID=${DOCKER_GID:-1000}
    container_name: artemiz-frontend-nginx
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - artemiz

  artemiz_npm:
    image: node:lts-alpine3.18
    container_name: artemiz-frontend-npm
    volumes:
      - ./:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - artemiz
